server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: "your-secret-key"
  expiration: 86400000 # 1 day in milliseconds

security:
  oauth2:
    client:
      registration:
        google:
          client-id: "your-google-client-id"
          client-secret: "your-google-client-secret"
          scope:
            - profile
            - email
